<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\AiQuicklyCategory
 *
 * @property int $cate_id
 * @property string|null $cate_name
 * @property int $sort_num
 * @property int $enable
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \App\Models\AiQuickly> $items
 * @property-read int|null $items_count
 * @method static Builder|AiQuicklyCategory newModelQuery()
 * @method static Builder|AiQuicklyCategory newQuery()
 * @method static Builder|AiQuicklyCategory query()
 * @method static Builder|AiQuicklyCategory whereCateId($value)
 * @method static Builder|AiQuicklyCategory whereCateName($value)
 * @method static Builder|AiQuicklyCategory whereEnable($value)
 * @method static Builder|AiQuicklyCategory whereSortNum($value)
 * @mixin \Eloquent
 */
class AiQuicklyCategory extends Model
{
    //use HasFactory;

    protected $table = 'ai_quickly_category';
    protected $primaryKey = 'cate_id';
    protected $fillable = ['cate_name', 'sort_num'];

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('sort', function (Builder $builder) {
            return $builder->orderByDesc('sort_num')->orderBy('cate_id');
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany|AiQuickly
     */
    public function items()
    {
        return $this->hasMany(AiQuickly::class, 'cate_id', 'cate_id');
    }
}
